/*
 * Create and Update Commercial Projects
 * This service enables you to create and  update commercial projects in a SAP  S/4HANA Cloud system. For example, you  can use this service to create a customer  or internal project based on an  opportunity or a quotation. 
 *
 * OpenAPI spec version: 1 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk._cpd_sc_proj_engmt_create_upd_srv.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.sap.apibhub.sdk._cpd_sc_proj_engmt_create_upd_srv.model.CollectionOfWorkPackage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CPDSCPROJENGMTCREATEUPDSRVProject
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-15T05:42:19.472Z")
public class CPDSCPROJENGMTCREATEUPDSRVProject {
  @SerializedName("ProjManagerCompCode")
  private String projManagerCompCode = null;

  @SerializedName("ProjAccountantCompCode")
  private String projAccountantCompCode = null;

  @SerializedName("ProjectID")
  private String projectID = null;

  @SerializedName("ProjControllerCompCode")
  private String projControllerCompCode = null;

  @SerializedName("ProjPartnerCompCode")
  private String projPartnerCompCode = null;

  @SerializedName("WorkPackageSet")
  private CollectionOfWorkPackage workPackageSet = null;

  public CPDSCPROJENGMTCREATEUPDSRVProject projManagerCompCode(String projManagerCompCode) {
    this.projManagerCompCode = projManagerCompCode;
    return this;
  }

   /**
   * Company Code   The company code is an organizational unit within financial accounting.
   * @return projManagerCompCode
  **/
  @ApiModelProperty(example = "null", value = "Company Code   The company code is an organizational unit within financial accounting.")
  public String getProjManagerCompCode() {
    return projManagerCompCode;
  }

  public void setProjManagerCompCode(String projManagerCompCode) {
    this.projManagerCompCode = projManagerCompCode;
  }

  public CPDSCPROJENGMTCREATEUPDSRVProject projAccountantCompCode(String projAccountantCompCode) {
    this.projAccountantCompCode = projAccountantCompCode;
    return this;
  }

   /**
   * Company Code   The company code is an organizational unit within financial accounting.
   * @return projAccountantCompCode
  **/
  @ApiModelProperty(example = "null", value = "Company Code   The company code is an organizational unit within financial accounting.")
  public String getProjAccountantCompCode() {
    return projAccountantCompCode;
  }

  public void setProjAccountantCompCode(String projAccountantCompCode) {
    this.projAccountantCompCode = projAccountantCompCode;
  }

  public CPDSCPROJENGMTCREATEUPDSRVProject projectID(String projectID) {
    this.projectID = projectID;
    return this;
  }

   /**
   * Commercial Project ID   Identifies a master project.
   * @return projectID
  **/
  @ApiModelProperty(example = "null", value = "Commercial Project ID   Identifies a master project.")
  public String getProjectID() {
    return projectID;
  }

  public void setProjectID(String projectID) {
    this.projectID = projectID;
  }

  public CPDSCPROJENGMTCREATEUPDSRVProject projControllerCompCode(String projControllerCompCode) {
    this.projControllerCompCode = projControllerCompCode;
    return this;
  }

   /**
   * Company Code   The company code is an organizational unit within financial accounting.
   * @return projControllerCompCode
  **/
  @ApiModelProperty(example = "null", value = "Company Code   The company code is an organizational unit within financial accounting.")
  public String getProjControllerCompCode() {
    return projControllerCompCode;
  }

  public void setProjControllerCompCode(String projControllerCompCode) {
    this.projControllerCompCode = projControllerCompCode;
  }

  public CPDSCPROJENGMTCREATEUPDSRVProject projPartnerCompCode(String projPartnerCompCode) {
    this.projPartnerCompCode = projPartnerCompCode;
    return this;
  }

   /**
   * Company Code   The company code is an organizational unit within financial accounting.
   * @return projPartnerCompCode
  **/
  @ApiModelProperty(example = "null", value = "Company Code   The company code is an organizational unit within financial accounting.")
  public String getProjPartnerCompCode() {
    return projPartnerCompCode;
  }

  public void setProjPartnerCompCode(String projPartnerCompCode) {
    this.projPartnerCompCode = projPartnerCompCode;
  }

  public CPDSCPROJENGMTCREATEUPDSRVProject workPackageSet(CollectionOfWorkPackage workPackageSet) {
    this.workPackageSet = workPackageSet;
    return this;
  }

   /**
   * Get workPackageSet
   * @return workPackageSet
  **/
  @ApiModelProperty(example = "null", value = "")
  public CollectionOfWorkPackage getWorkPackageSet() {
    return workPackageSet;
  }

  public void setWorkPackageSet(CollectionOfWorkPackage workPackageSet) {
    this.workPackageSet = workPackageSet;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CPDSCPROJENGMTCREATEUPDSRVProject cpDSCPROJENGMTCREATEUPDSRVProject = (CPDSCPROJENGMTCREATEUPDSRVProject) o;
    return Objects.equals(this.projManagerCompCode, cpDSCPROJENGMTCREATEUPDSRVProject.projManagerCompCode) &&
        Objects.equals(this.projAccountantCompCode, cpDSCPROJENGMTCREATEUPDSRVProject.projAccountantCompCode) &&
        Objects.equals(this.projectID, cpDSCPROJENGMTCREATEUPDSRVProject.projectID) &&
        Objects.equals(this.projControllerCompCode, cpDSCPROJENGMTCREATEUPDSRVProject.projControllerCompCode) &&
        Objects.equals(this.projPartnerCompCode, cpDSCPROJENGMTCREATEUPDSRVProject.projPartnerCompCode) &&
        Objects.equals(this.workPackageSet, cpDSCPROJENGMTCREATEUPDSRVProject.workPackageSet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projManagerCompCode, projAccountantCompCode, projectID, projControllerCompCode, projPartnerCompCode, workPackageSet);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CPDSCPROJENGMTCREATEUPDSRVProject {\n");
    
    sb.append("    projManagerCompCode: ").append(toIndentedString(projManagerCompCode)).append("\n");
    sb.append("    projAccountantCompCode: ").append(toIndentedString(projAccountantCompCode)).append("\n");
    sb.append("    projectID: ").append(toIndentedString(projectID)).append("\n");
    sb.append("    projControllerCompCode: ").append(toIndentedString(projControllerCompCode)).append("\n");
    sb.append("    projPartnerCompCode: ").append(toIndentedString(projPartnerCompCode)).append("\n");
    sb.append("    workPackageSet: ").append(toIndentedString(workPackageSet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

