/*
 * Create and Update Commercial Projects
 * This service enables you to create and  update commercial projects in a SAP  S/4HANA Cloud system. For example, you  can use this service to create a customer  or internal project based on an  opportunity or a quotation. 
 *
 * OpenAPI spec version: 1 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk._cpd_sc_proj_engmt_create_upd_srv.api;

import com.sap.apibhub.sdk.client.ApiCallback;
import com.sap.apibhub.sdk.client.ApiClient;
import com.sap.apibhub.sdk.client.ApiException;
import com.sap.apibhub.sdk.client.ApiResponse;
import com.sap.apibhub.sdk.client.Configuration;
import com.sap.apibhub.sdk.client.Pair;
import com.sap.apibhub.sdk.client.ProgressRequestBody;
import com.sap.apibhub.sdk.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.sap.apibhub.sdk._cpd_sc_proj_engmt_create_upd_srv.model.CPDSCPROJENGMTCREATEUPDSRVDemand;
import com.sap.apibhub.sdk._cpd_sc_proj_engmt_create_upd_srv.model.CreatedDemand;
import com.sap.apibhub.sdk._cpd_sc_proj_engmt_create_upd_srv.model.ModifiedDemand;
import com.sap.apibhub.sdk._cpd_sc_proj_engmt_create_upd_srv.model.OdataError;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DemandSetApi {
    private ApiClient apiClient;

    public DemandSetApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DemandSetApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for demandSetPost */
    private com.squareup.okhttp.Call demandSetPostCall(CPDSCPROJENGMTCREATEUPDSRVDemand demand, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = demand;
        
        // create path and map variables
        String localVarPath = "/DemandSet".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call demandSetPostValidateBeforeCall(CPDSCPROJENGMTCREATEUPDSRVDemand demand, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = demandSetPostCall(demand, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Add new entity to DemandSet
     * 
     * @param demand New entity (optional)
     * @return CreatedDemand
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public CreatedDemand demandSetPost(CPDSCPROJENGMTCREATEUPDSRVDemand demand) throws ApiException {
        ApiResponse<CreatedDemand> resp = demandSetPostWithHttpInfo(demand);
        return resp.getData();
    }

    /**
     * Add new entity to DemandSet
     * 
     * @param demand New entity (optional)
     * @return ApiResponse&lt;CreatedDemand&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<CreatedDemand> demandSetPostWithHttpInfo(CPDSCPROJENGMTCREATEUPDSRVDemand demand) throws ApiException {
        com.squareup.okhttp.Call call = demandSetPostValidateBeforeCall(demand, null, null);
        Type localVarReturnType = new TypeToken<CreatedDemand>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Add new entity to DemandSet (asynchronously)
     * 
     * @param demand New entity (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call demandSetPostAsync(CPDSCPROJENGMTCREATEUPDSRVDemand demand, final ApiCallback<CreatedDemand> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = demandSetPostValidateBeforeCall(demand, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<CreatedDemand>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDelete */
    private com.squareup.okhttp.Call demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDeleteCall(String projectID, String workPackageID, String workPackageName, String resType, String resourceId, String workitem, String delvryServOrg, String ifMatch, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/DemandSet(ProjectID='{ProjectID}',WorkPackageID='{WorkPackageID}',WorkPackageName='{WorkPackageName}',ResType='{ResType}',ResourceId='{ResourceId}',Workitem='{Workitem}',DelvryServOrg='{DelvryServOrg}')".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "ProjectID" + "\\}", apiClient.escapeString(projectID.toString()))
        .replaceAll("\\{" + "WorkPackageID" + "\\}", apiClient.escapeString(workPackageID.toString()))
        .replaceAll("\\{" + "WorkPackageName" + "\\}", apiClient.escapeString(workPackageName.toString()))
        .replaceAll("\\{" + "ResType" + "\\}", apiClient.escapeString(resType.toString()))
        .replaceAll("\\{" + "ResourceId" + "\\}", apiClient.escapeString(resourceId.toString()))
        .replaceAll("\\{" + "Workitem" + "\\}", apiClient.escapeString(workitem.toString()))
        .replaceAll("\\{" + "DelvryServOrg" + "\\}", apiClient.escapeString(delvryServOrg.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        if (ifMatch != null)
        localVarHeaderParams.put("If-Match", apiClient.parameterToString(ifMatch));

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDeleteValidateBeforeCall(String projectID, String workPackageID, String workPackageName, String resType, String resourceId, String workitem, String delvryServOrg, String ifMatch, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'projectID' is set
        if (projectID == null) {
            throw new ApiException("Missing the required parameter 'projectID' when calling demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDelete(Async)");
        }
        
        // verify the required parameter 'workPackageID' is set
        if (workPackageID == null) {
            throw new ApiException("Missing the required parameter 'workPackageID' when calling demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDelete(Async)");
        }
        
        // verify the required parameter 'workPackageName' is set
        if (workPackageName == null) {
            throw new ApiException("Missing the required parameter 'workPackageName' when calling demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDelete(Async)");
        }
        
        // verify the required parameter 'resType' is set
        if (resType == null) {
            throw new ApiException("Missing the required parameter 'resType' when calling demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDelete(Async)");
        }
        
        // verify the required parameter 'resourceId' is set
        if (resourceId == null) {
            throw new ApiException("Missing the required parameter 'resourceId' when calling demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDelete(Async)");
        }
        
        // verify the required parameter 'workitem' is set
        if (workitem == null) {
            throw new ApiException("Missing the required parameter 'workitem' when calling demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDelete(Async)");
        }
        
        // verify the required parameter 'delvryServOrg' is set
        if (delvryServOrg == null) {
            throw new ApiException("Missing the required parameter 'delvryServOrg' when calling demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDelete(Async)");
        }
        
        
        com.squareup.okhttp.Call call = demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDeleteCall(projectID, workPackageID, workPackageName, resType, resourceId, workitem, delvryServOrg, ifMatch, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Delete entity from DemandSet
     * 
     * @param projectID Commercial Project ID   Identifies a master project. (required)
     * @param workPackageID Plan Item (required)
     * @param workPackageName Plan Item Description (required)
     * @param resType Used to uniquely identify the resource type.   Resource types are used to categorize resources while carrying out financial planning activities. (required)
     * @param resourceId Resource ID   Used to uniquely identify a resource.   Resources correspond to individual entities in a project. You can assign multiple cost elements and activity types to each resource. (required)
     * @param workitem Work Item ID (required)
     * @param delvryServOrg Service Organization   This field links master project data with the company code and plant.   This field links master project data with the company code and plant. (required)
     * @param ifMatch ETag (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDelete(String projectID, String workPackageID, String workPackageName, String resType, String resourceId, String workitem, String delvryServOrg, String ifMatch) throws ApiException {
        demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDeleteWithHttpInfo(projectID, workPackageID, workPackageName, resType, resourceId, workitem, delvryServOrg, ifMatch);
    }

    /**
     * Delete entity from DemandSet
     * 
     * @param projectID Commercial Project ID   Identifies a master project. (required)
     * @param workPackageID Plan Item (required)
     * @param workPackageName Plan Item Description (required)
     * @param resType Used to uniquely identify the resource type.   Resource types are used to categorize resources while carrying out financial planning activities. (required)
     * @param resourceId Resource ID   Used to uniquely identify a resource.   Resources correspond to individual entities in a project. You can assign multiple cost elements and activity types to each resource. (required)
     * @param workitem Work Item ID (required)
     * @param delvryServOrg Service Organization   This field links master project data with the company code and plant.   This field links master project data with the company code and plant. (required)
     * @param ifMatch ETag (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDeleteWithHttpInfo(String projectID, String workPackageID, String workPackageName, String resType, String resourceId, String workitem, String delvryServOrg, String ifMatch) throws ApiException {
        com.squareup.okhttp.Call call = demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDeleteValidateBeforeCall(projectID, workPackageID, workPackageName, resType, resourceId, workitem, delvryServOrg, ifMatch, null, null);
        return apiClient.execute(call);
    }

    /**
     * Delete entity from DemandSet (asynchronously)
     * 
     * @param projectID Commercial Project ID   Identifies a master project. (required)
     * @param workPackageID Plan Item (required)
     * @param workPackageName Plan Item Description (required)
     * @param resType Used to uniquely identify the resource type.   Resource types are used to categorize resources while carrying out financial planning activities. (required)
     * @param resourceId Resource ID   Used to uniquely identify a resource.   Resources correspond to individual entities in a project. You can assign multiple cost elements and activity types to each resource. (required)
     * @param workitem Work Item ID (required)
     * @param delvryServOrg Service Organization   This field links master project data with the company code and plant.   This field links master project data with the company code and plant. (required)
     * @param ifMatch ETag (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDeleteAsync(String projectID, String workPackageID, String workPackageName, String resType, String resourceId, String workitem, String delvryServOrg, String ifMatch, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgDeleteValidateBeforeCall(projectID, workPackageID, workPackageName, resType, resourceId, workitem, delvryServOrg, ifMatch, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /* Build call for demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatch */
    private com.squareup.okhttp.Call demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatchCall(String projectID, String workPackageID, String workPackageName, String resType, String resourceId, String workitem, String delvryServOrg, ModifiedDemand demand, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = demand;
        
        // create path and map variables
        String localVarPath = "/DemandSet(ProjectID='{ProjectID}',WorkPackageID='{WorkPackageID}',WorkPackageName='{WorkPackageName}',ResType='{ResType}',ResourceId='{ResourceId}',Workitem='{Workitem}',DelvryServOrg='{DelvryServOrg}')".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "ProjectID" + "\\}", apiClient.escapeString(projectID.toString()))
        .replaceAll("\\{" + "WorkPackageID" + "\\}", apiClient.escapeString(workPackageID.toString()))
        .replaceAll("\\{" + "WorkPackageName" + "\\}", apiClient.escapeString(workPackageName.toString()))
        .replaceAll("\\{" + "ResType" + "\\}", apiClient.escapeString(resType.toString()))
        .replaceAll("\\{" + "ResourceId" + "\\}", apiClient.escapeString(resourceId.toString()))
        .replaceAll("\\{" + "Workitem" + "\\}", apiClient.escapeString(workitem.toString()))
        .replaceAll("\\{" + "DelvryServOrg" + "\\}", apiClient.escapeString(delvryServOrg.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "PATCH", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatchValidateBeforeCall(String projectID, String workPackageID, String workPackageName, String resType, String resourceId, String workitem, String delvryServOrg, ModifiedDemand demand, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'projectID' is set
        if (projectID == null) {
            throw new ApiException("Missing the required parameter 'projectID' when calling demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatch(Async)");
        }
        
        // verify the required parameter 'workPackageID' is set
        if (workPackageID == null) {
            throw new ApiException("Missing the required parameter 'workPackageID' when calling demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatch(Async)");
        }
        
        // verify the required parameter 'workPackageName' is set
        if (workPackageName == null) {
            throw new ApiException("Missing the required parameter 'workPackageName' when calling demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatch(Async)");
        }
        
        // verify the required parameter 'resType' is set
        if (resType == null) {
            throw new ApiException("Missing the required parameter 'resType' when calling demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatch(Async)");
        }
        
        // verify the required parameter 'resourceId' is set
        if (resourceId == null) {
            throw new ApiException("Missing the required parameter 'resourceId' when calling demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatch(Async)");
        }
        
        // verify the required parameter 'workitem' is set
        if (workitem == null) {
            throw new ApiException("Missing the required parameter 'workitem' when calling demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatch(Async)");
        }
        
        // verify the required parameter 'delvryServOrg' is set
        if (delvryServOrg == null) {
            throw new ApiException("Missing the required parameter 'delvryServOrg' when calling demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatch(Async)");
        }
        
        
        com.squareup.okhttp.Call call = demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatchCall(projectID, workPackageID, workPackageName, resType, resourceId, workitem, delvryServOrg, demand, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Update entity in DemandSet
     * 
     * @param projectID Commercial Project ID   Identifies a master project. (required)
     * @param workPackageID Plan Item (required)
     * @param workPackageName Plan Item Description (required)
     * @param resType Used to uniquely identify the resource type.   Resource types are used to categorize resources while carrying out financial planning activities. (required)
     * @param resourceId Resource ID   Used to uniquely identify a resource.   Resources correspond to individual entities in a project. You can assign multiple cost elements and activity types to each resource. (required)
     * @param workitem Work Item ID (required)
     * @param delvryServOrg Service Organization   This field links master project data with the company code and plant.   This field links master project data with the company code and plant. (required)
     * @param demand New property values (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatch(String projectID, String workPackageID, String workPackageName, String resType, String resourceId, String workitem, String delvryServOrg, ModifiedDemand demand) throws ApiException {
        demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatchWithHttpInfo(projectID, workPackageID, workPackageName, resType, resourceId, workitem, delvryServOrg, demand);
    }

    /**
     * Update entity in DemandSet
     * 
     * @param projectID Commercial Project ID   Identifies a master project. (required)
     * @param workPackageID Plan Item (required)
     * @param workPackageName Plan Item Description (required)
     * @param resType Used to uniquely identify the resource type.   Resource types are used to categorize resources while carrying out financial planning activities. (required)
     * @param resourceId Resource ID   Used to uniquely identify a resource.   Resources correspond to individual entities in a project. You can assign multiple cost elements and activity types to each resource. (required)
     * @param workitem Work Item ID (required)
     * @param delvryServOrg Service Organization   This field links master project data with the company code and plant.   This field links master project data with the company code and plant. (required)
     * @param demand New property values (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatchWithHttpInfo(String projectID, String workPackageID, String workPackageName, String resType, String resourceId, String workitem, String delvryServOrg, ModifiedDemand demand) throws ApiException {
        com.squareup.okhttp.Call call = demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatchValidateBeforeCall(projectID, workPackageID, workPackageName, resType, resourceId, workitem, delvryServOrg, demand, null, null);
        return apiClient.execute(call);
    }

    /**
     * Update entity in DemandSet (asynchronously)
     * 
     * @param projectID Commercial Project ID   Identifies a master project. (required)
     * @param workPackageID Plan Item (required)
     * @param workPackageName Plan Item Description (required)
     * @param resType Used to uniquely identify the resource type.   Resource types are used to categorize resources while carrying out financial planning activities. (required)
     * @param resourceId Resource ID   Used to uniquely identify a resource.   Resources correspond to individual entities in a project. You can assign multiple cost elements and activity types to each resource. (required)
     * @param workitem Work Item ID (required)
     * @param delvryServOrg Service Organization   This field links master project data with the company code and plant.   This field links master project data with the company code and plant. (required)
     * @param demand New property values (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatchAsync(String projectID, String workPackageID, String workPackageName, String resType, String resourceId, String workitem, String delvryServOrg, ModifiedDemand demand, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = demandSetProjectIDProjectIDWorkPackageIDWorkPackageIDWorkPackageNameWorkPackageNameResTypeResTypeResourceIdResourceIdWorkitemWorkitemDelvryServOrgDelvryServOrgPatchValidateBeforeCall(projectID, workPackageID, workPackageName, resType, resourceId, workitem, delvryServOrg, demand, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
}
