/*
 * Create and Update Commercial Projects
 * This service enables you to create and  update commercial projects in a SAP  S/4HANA Cloud system. For example, you  can use this service to create a customer  or internal project based on an  opportunity or a quotation. 
 *
 * OpenAPI spec version: 1 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk._cpd_sc_proj_engmt_create_upd_srv.api;

import com.sap.apibhub.sdk.client.ApiCallback;
import com.sap.apibhub.sdk.client.ApiClient;
import com.sap.apibhub.sdk.client.ApiException;
import com.sap.apibhub.sdk.client.ApiResponse;
import com.sap.apibhub.sdk.client.Configuration;
import com.sap.apibhub.sdk.client.Pair;
import com.sap.apibhub.sdk.client.ProgressRequestBody;
import com.sap.apibhub.sdk.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.sap.apibhub.sdk._cpd_sc_proj_engmt_create_upd_srv.model.CPDSCPROJENGMTCREATEUPDSRVProject;
import com.sap.apibhub.sdk._cpd_sc_proj_engmt_create_upd_srv.model.CreatedProject;
import com.sap.apibhub.sdk._cpd_sc_proj_engmt_create_upd_srv.model.ModifiedProject;
import com.sap.apibhub.sdk._cpd_sc_proj_engmt_create_upd_srv.model.OdataError;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ProjectSetApi {
    private ApiClient apiClient;

    public ProjectSetApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ProjectSetApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for projectSetPost */
    private com.squareup.okhttp.Call projectSetPostCall(CPDSCPROJENGMTCREATEUPDSRVProject project, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = project;
        
        // create path and map variables
        String localVarPath = "/ProjectSet".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call projectSetPostValidateBeforeCall(CPDSCPROJENGMTCREATEUPDSRVProject project, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = projectSetPostCall(project, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Add new entity to ProjectSet
     * 
     * @param project New entity (optional)
     * @return CreatedProject
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public CreatedProject projectSetPost(CPDSCPROJENGMTCREATEUPDSRVProject project) throws ApiException {
        ApiResponse<CreatedProject> resp = projectSetPostWithHttpInfo(project);
        return resp.getData();
    }

    /**
     * Add new entity to ProjectSet
     * 
     * @param project New entity (optional)
     * @return ApiResponse&lt;CreatedProject&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<CreatedProject> projectSetPostWithHttpInfo(CPDSCPROJENGMTCREATEUPDSRVProject project) throws ApiException {
        com.squareup.okhttp.Call call = projectSetPostValidateBeforeCall(project, null, null);
        Type localVarReturnType = new TypeToken<CreatedProject>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Add new entity to ProjectSet (asynchronously)
     * 
     * @param project New entity (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call projectSetPostAsync(CPDSCPROJENGMTCREATEUPDSRVProject project, final ApiCallback<CreatedProject> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = projectSetPostValidateBeforeCall(project, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<CreatedProject>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for projectSetProjectIDPatch */
    private com.squareup.okhttp.Call projectSetProjectIDPatchCall(String projectID, ModifiedProject project, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = project;
        
        // create path and map variables
        String localVarPath = "/ProjectSet('{ProjectID}')".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "ProjectID" + "\\}", apiClient.escapeString(projectID.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "PATCH", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call projectSetProjectIDPatchValidateBeforeCall(String projectID, ModifiedProject project, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'projectID' is set
        if (projectID == null) {
            throw new ApiException("Missing the required parameter 'projectID' when calling projectSetProjectIDPatch(Async)");
        }
        
        
        com.squareup.okhttp.Call call = projectSetProjectIDPatchCall(projectID, project, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Update entity in ProjectSet
     * 
     * @param projectID Commercial Project ID   Identifies a master project. (required)
     * @param project New property values (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void projectSetProjectIDPatch(String projectID, ModifiedProject project) throws ApiException {
        projectSetProjectIDPatchWithHttpInfo(projectID, project);
    }

    /**
     * Update entity in ProjectSet
     * 
     * @param projectID Commercial Project ID   Identifies a master project. (required)
     * @param project New property values (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> projectSetProjectIDPatchWithHttpInfo(String projectID, ModifiedProject project) throws ApiException {
        com.squareup.okhttp.Call call = projectSetProjectIDPatchValidateBeforeCall(projectID, project, null, null);
        return apiClient.execute(call);
    }

    /**
     * Update entity in ProjectSet (asynchronously)
     * 
     * @param projectID Commercial Project ID   Identifies a master project. (required)
     * @param project New property values (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call projectSetProjectIDPatchAsync(String projectID, ModifiedProject project, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = projectSetProjectIDPatchValidateBeforeCall(projectID, project, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
}
